### ISSUE TITLE
Rancher 1.2 changes container names

### ISSUE THREAD

**Issue by mathuin** [Munsio/rancher-cattle-nginx-letsencrypt#3]
Container names in 1.2 are now "r-stack-service-index-firstSegmentOfUUID" according to vincent99.  This breaks the config file for the docker-gen, and may contribute to the trampolining I'm seeing with the nginx container.

**Comment by Munsio** [comment]
Hi @mathuin. You are right, i fixed this problem already in another repo. Pls use ranchers upgrade service and be sure to tick the "pull image" checkbox on the letsencrypt sudekick to get the updated version.

**Comment by mathuin** [comment]
Okay, did that!  Will a later reinstall of the catalog entry use the new version of the sidekick?  I *think* so, but I'm not as familiar with catalog entries and how they work.

**Comment by Munsio** [comment]
rancher-catalog uses the normal docker-compose.yml and in there it is referenced as latest so for further installs over the catalog there should be no problem.
